### ISSUE TITLE
Cannot open game after putting in files

### ISSUE THREAD

**Issue by wowm03** [Booplicate/MAS-Submods-YouTubeMusic#28]
As the title suggests, im failing to open the game after following all the instructions including putting in 'libs', 'python packages', 'submods' and such. Mac user, so i have indeed put in the '_ssl.so' and 'ssl.pyo' files inside too. I'm not sure if i've done anything wrong or it's because that i'm using Doki Doki Manager. Thank you.

**Comment by wowm03** [comment]
Error: spawn /Users/(User)/Library/Application Support/DokiDokiModManager/GameData/installs/ddlc-mas/install/MacOS/DDLC ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by wowm03** [comment]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 179, in <module>
    youtube_dl.std_headers["User-Agent"] = ytm_globals.YDL_OPTS["user_agent"]
AttributeError: 'module' object has no attribute 'std_headers'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/(user)/Library/Application Support/DokiDokiModManager/GameData/installs/ddlc-mas/install/Submods/YouTube Music/ytm_utils.rpyc", line 164, in script
  File "/Users/(user)/Library/Application Support/DokiDokiModManager/GameData/installs/ddlc-mas/install/Resources/autorun/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/(user)/Library/Application Support/DokiDokiModManager/GameData/installs/ddlc-mas/install/Resources/autorun/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 179, in <module>
    youtube_dl.std_headers["User-Agent"] = ytm_globals.YDL_OPTS["user_agent"]
AttributeError: 'module' object has no attribute 'std_headers'

Darwin-21.2.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8

**Comment by Booplicate** [comment]
Mod managers don't work too well, can you try to run w/o it?

**Comment by wowm03** [comment]
So it’s that that caused the problem, yes, i’ll try that later, thank you! I’ll tell if there still are any problems or not after i tried it.

**Comment by wowm03** [comment]
> Mod managers don't work too well, can you try to run w/o it?

### Not quite working
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
    init python in ytm_utils:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 179, in <module>
    youtube_dl.std_headers["User-Agent"] = ytm_globals.YDL_OPTS["user_agent"]
AttributeError: 'module' object has no attribute 'std_headers'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
    init python in ytm_utils:
  File "/Users/(user)/Desktop/DDLC.app/Contents/Resources/autorun/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/(user)/Desktop/DDLC.app/Contents/Resources/autorun/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 179, in <module>
    youtube_dl.std_headers["User-Agent"] = ytm_globals.YDL_OPTS["user_agent"]
AttributeError: 'module' object has no attribute 'std_headers'

Darwin-21.2.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8
[/code]

**Comment by wowm03** [comment]
[traceback.txt](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/8648757/traceback.txt)

**Comment by Booplicate** [comment]
I can't reproduce this and the error doesn't make much sense if the submod was installed correctly. It looks like `python-packages` are missing some sub-modules.
